DealDouble.Web/ViewModels/AuctionViewModels.cs
using DealDouble.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DealDouble.Web.ViewModels
{
    public class AuctionListingViewModel : PageViewModel
    {
        public List<Auction> Auctions { get; set; }
        public int? CategoryID { get; set; }
        public string SearchTerm { get; set; }
        public int? PageNo { get; set; }
        public Pager Pager { get; set; }
    }

    public class AuctionViewModel : PageViewModel
    {
        public List<Auction> AllAuctions { get; set; }
        public List<Auction> PromotedAuctions { get; set; }
        
    }
    public class AuctionDetailsViewModel : PageViewModel
    {
        public Auction Auction { get; set; }
    }
    public class CreateAuctionViewModel : PageViewModel
    {
        public int ID { get; set; }
        public int CategoryID { get; set; }
        [Required]
        [MinLength(5, ErrorMessage = "Minimun length should be 5 characters")]
        [MaxLength(150, ErrorMessage = "Maximun length should be 5 characters")]
        public string Title { get; set; }
        public string Description { get; set; }
        [Required]
        [Range(100, 10000, ErrorMessage = "Actual amount range should from 100 to 10000")]
        public decimal ActualAmount { get; set; }
        public DateTime? StartingTime { get; set; }
        public DateTime? EndingTime { get; set; }
        public string Auctionpictures { get; set; }
        public List<Category> Categories { get; set; }
        public List<AuctionPicture> AuctionPicturesList { get; set; }
    }
}

DealDouble.Web/Controllers/AuctionsController.cs
using DealDouble.Entities;
using DealDouble.Web.ViewModels;
using DealDoubleServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DealDouble.Web.Controllers
{
    public class AuctionsController : Controller
    {
        AuctionsService auctionsService = new AuctionsService();
        CategoriesService categoriesService = new CategoriesService();
        // GET: Auctions
        public ActionResult Index(int? categoryID, string SearchTerm, int? pageNo)
        {
            
            AuctionListingViewModel model = new AuctionListingViewModel();
            model.PageTitle = "Auctions";
            model.PageDescription = "Auction listing page";

            model.CategoryID = categoryID;
            model.SearchTerm = SearchTerm;
            model.PageNo = pageNo;

            return View(model);
            
        }

        public ActionResult Listing( int? categoryID, string searchTerm, int? pageNo)
        {
            var pageSize = 5 ;
            AuctionListingViewModel model = new AuctionListingViewModel();
            model.Auctions = auctionsService.SearchAuctions(categoryID , searchTerm, pageNo, pageSize);
            var totalAuctions = auctionsService.GetAuctionCount();

            model.Pager = new Pager(totalAuctions, pageNo, pageSize);
            
            return PartialView(model);
            
        }
        public ActionResult Create()
        {
            CreateAuctionViewModel model = new CreateAuctionViewModel();
            model.Categories = categoriesService.GetAllCategories();
            return PartialView(model);
        }
        [HttpPost]
        public JsonResult Create(CreateAuctionViewModel model)
        {
            JsonResult result = new JsonResult();
            if (ModelState.IsValid)
            {

                Auction auction = new Auction();
                auction.Title = model.Title;
                auction.CategoryID = model.CategoryID;
                auction.Description = model.Description;
                auction.ActualAmount = model.ActualAmount;
                auction.StartingTime = model.StartingTime;
                auction.EndingTime = model.EndingTime;

                if (!string.IsNullOrEmpty(model.Auctionpictures))
                {
                    //LINQ
                    var pictureIDs = model.Auctionpictures.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries).Select(ID => int.Parse(ID)).ToList();
                    auction.AuctionPictures = new List<AuctionPicture>();
                    auction.AuctionPictures.AddRange(pictureIDs.Select(x => new AuctionPicture() { PictureID = x }).ToList());

                    /* the above line means:
                    foreach (var picIDs in pictureIDs)
                    {
                        AuctionPicture auctionPicture = new AuctionPicture();
                        auctionPicture.PictureID = picIDs;
                        auction.AuctionPictures.Add(auctionPicture);
                    }*/
                }
                auctionsService.SaveAuction(auction);
                result.Data = new { Success = true };
            }
            else
            {
                result.Data = new { Success = false, Error= "Unable to save Auction, please enter valid values!" };
            }
            return result;
        }

        public ActionResult Edit(int ID)
        {
            CreateAuctionViewModel model = new CreateAuctionViewModel();
            var auction = auctionsService.GetAuctionByID(ID);
            model.ID = auction.ID;
            model.Title = auction.Title;
            model.CategoryID = auction.CategoryID;
            model.Description = auction.Description;
            model.ActualAmount = auction.ActualAmount;
            model.StartingTime = auction.StartingTime;
            model.EndingTime = auction.EndingTime;

            model.Categories = categoriesService.GetAllCategories();
            model.AuctionPicturesList = auction.AuctionPictures;

            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Edit(CreateAuctionViewModel model)
        {
            Auction auction = new Auction();
            auction.ID = model.ID;
            auction.Title = model.Title;
            auction.CategoryID = model.CategoryID;
            auction.Description = model.Description;
            auction.ActualAmount = model.ActualAmount;
            auction.StartingTime = model.StartingTime;
            auction.EndingTime = model.EndingTime;

            if (!string.IsNullOrEmpty(model.Auctionpictures))
            {
                //LINQ
                var pictureIDs = model.Auctionpictures.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries).Select(ID => int.Parse(ID)).ToList();
                auction.AuctionPictures = new List<AuctionPicture>();
                auction.AuctionPictures.AddRange(pictureIDs.Select(x => new AuctionPicture() { PictureID = x }).ToList());
            }

            auctionsService.UpdateAuction(auction);
            return RedirectToAction("Listing");
        }

        [HttpPost]
        public ActionResult Delete(Auction auction)
        {
                auctionsService.DeleteAuction(auction);
                return RedirectToAction("Listing");
        }

        public ActionResult Details(int ID)
        {
             AuctionDetailsViewModel model = new AuctionDetailsViewModel();
           
            model.Auction = auctionsService.GetAuctionByID(ID);

            model.PageTitle = "Auction Details:"+ model.Auction.Title;
            model.PageDescription = model.Auction.Description.Substring(0,10);
            return View(model);
        }

    }

}

DealDouble.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using DealDouble.Entities;
using DealDoubleServices;

namespace DealDouble.Web.Controllers
{
    public class SharedController : Controller
    {
        SharedServices service = new SharedServices();
        [HttpPost]
        public JsonResult UploadPictures()
        {
            JsonResult result = new JsonResult();
            List<object> picturesJSON = new List<object>();

            var pictures = Request.Files;
            for (int i = 0; i < pictures.Count; i++)
            {
                var picture = pictures[i];
             
                var filename =Guid.NewGuid() + Path.GetExtension(picture.FileName);
                var path = Server.MapPath("~/Content/images/") + filename;
                picture.SaveAs(path);

                Picture dbPicture = new Picture();
                dbPicture.URL = filename;

                int pictureID = service.SavePicture(dbPicture);

                picturesJSON.Add(new { ID = pictureID, pictureURL = filename });
            }
            result.Data=picturesJSON;
            return result;
        }
    }
}

DealDouble.Web/Views/Auctions/Create.cshtml
@model DealDouble.Web.ViewModels.CreateAuctionViewModel


<div class="modal-header">
    <h5 class="modal-title">Create Auction</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<form id="CreateForm" method="post" action="/auctions/create">

 
    <div class="modal-body">
        <div class="form-group">
            <label>Title</label>
            <input class="form-control" name="Title" value=@Model.Title />
        </div>

        <div class="form-group">
            <label>Category</label>
            <select class="form-control" name="CategoryID">
                @foreach (var category in Model.Categories)
                {
                    <option value="@category.ID">@category.Name</option>
                }
            </select>
        </div>

        <div class="form-group">
            <label> Description</label>
            <input class="form-control" name="Description" value=@Model.Description />
        </div>

        <div class="form-group">
            <label>ActualAmount</label>
            <input class="form-control" name="ActualAmount" value=@Model.ActualAmount />
        </div>

        <div class="form-group">
            <label>StartingTime</label>
            <input class="form-control" name="StartingTime" value=@Model.StartingTime />
        </div>

        <div class="form-group">
            <label>EndingTime</label>
            <input class="form-control" name="EndingTime" value=@Model.EndingTime />
        </div>
        <div class="form-group">
            <label>Select pictures</label>
            <input id="AuctionPictures" class="form-control" name="AuctionPictures" type="file" multiple />
            <div id="picturesArea" class="mt-2"></div>
            <input type="hidden" name="Auctionpictures" id="pictureIDs" />
        </div> 
        <div id="formErrors" class="form-group bg-danger" style="display:none" >
        </div>
        
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button class="btn btn-primary" type="button" id="SaveButton">Save</button>
    </div>
</form>


<script>
    $("#CreateForm").validate({
        rules: {
            Title: {
                required: true,
                minlength: 5,
                maxlength: 150
            }
        },
        messages: {
             Title: {
                required: "Title is required",
                minlength: "Minimum length is 5",
                maxlength: "Maximum length is 150"
            }
        }
    });
    $("#SaveButton").click(function () {
        if ($("#CreateForm").valid())
        {
            var imageIDs = [];
            $("#picturesArea .image").each(function () {
                var imageID = $(this).attr("data-id");
                imageIDs.push(imageID);
            });
            $("#pictureIDs").val(imageIDs.join());
            $.ajax({
                url: "@Url.Action("Create","Auctions")",
                type: "post",
                data: $("#CreateForm").serialize()
            }).done(function (response) {
                if (response.Success) {
                    ReloadListing();
                    $("#formModal").modal("toggle");
                }
                else {
                    $("#formErrors").html(response.Error);
                    $("#formErrors").show();
                }
            });
        }
    });

    $("#AuctionPictures").change(function () {
        var pictures = this.files;
        var picsData = new FormData();
        for (var i = 0; i < pictures.length; i++) {
            picsData.append("Picture", pictures[i]);
        }
        $.ajax({
            url: "@Url.Action("UploadPictures","Shared")",
            method: "post",
            data: picsData,
            dataType: "json",
            processData: false,
            contentType: false

        }).done(function (responses) {
            debugger;
            for (var i = 0; i < responses.length; i++) {
                var picResponse = responses[i];
                debugger;
                AttachNewImage(picResponse.pictureURL, picResponse.ID);

            }
        });
    });


</script>

DealDouble.Web/Views/Auctions/Details.cshtml
@model DealDouble.Web.ViewModels.AuctionDetailsViewModel
@*@model DealDouble.Web.ViewModels.AuctionListingViewModel*@


<div class="row">

    <div class="col-lg-12">

        <div class="card mt-4">
            @if (Model.Auction.AuctionPictures != null && Model.Auction.AuctionPictures.Count > 0)
            {
                var firstAuctionPicture = Model.Auction.AuctionPictures.First();
                var i=0;
                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">

                        @foreach (var picture in Model.Auction.AuctionPictures)
                        {
                            var active = picture == firstAuctionPicture ? "active" : string.Empty;
                            <li class="@active" data-target="#carouselIndicators" data-slide-to="@i"></li>
                            i++;
                        }
                    </ol>
                    <div class="carousel-inner" role="listbox">

                        @foreach (var auctionPicture in Model.Auction.AuctionPictures)
                        {
                            var active = auctionPicture == firstAuctionPicture ? "active" : string.Empty;
                            var picURL = "/Content/images/" + auctionPicture.Picture.URL;
                        <div class="carousel-item @active">
                            <img class="d-block img-fluid" src="@picURL">
                        </div>
                        }
                    </div>
                    <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            }


            <div class="card-body">
                <h3 class="card-title">@Model.Auction.Title</h3>
                <h4>$@Model.Auction.ActualAmount</h4>
                <p class="card-text">@Model.Auction.Description</p>
                <span class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</span>
                4.0 stars
            </div>
        </div>
        <!-- /.card -->

        <div class="card card-outline-secondary my-4">
            <div class="card-header">
                Product Reviews
            </div>
            <div class="card-body">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
                <small class="text-muted">Posted by Anonymous on 3/1/17</small>
                <hr>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
                <small class="text-muted">Posted by Anonymous on 3/1/17</small>
                <hr>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
                <small class="text-muted">Posted by Anonymous on 3/1/17</small>
                <hr>
                <a href="#" class="btn btn-success">Leave a Review</a>
            </div>
        </div>
        <!-- /.card -->

    </div>
    <!-- /.col-lg-9 -->

</div>

DealDouble.Web/Views/Auctions/Edit.cshtml
@model DealDouble.Web.ViewModels.CreateAuctionViewModel


<div class="modal-header">
    <h5 class="modal-title">Edit Auction</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<form id="EditForm">


    <div class="modal-body">
        <input type="hidden" name="ID" value="@Model.ID" />


        <div class="form-group">
            <label>Title</label>
            <input class="form-control" name="Title" value="@Model.Title" />
        </div>

        <div class="form-group">
            <label>Description</label>
            <select class="form-control" name="CategoryID">
                @foreach (var category in Model.Categories)
                {
                    var selected = category.ID == Model.CategoryID ? "selected" : string.Empty;
                    <option value="@category.ID" @selected>@category.Name</option>
                }
            </select>
        </div>

        <div class="form-group">
            <label> Description</label>
            <input class="form-control" name="Description" value="@Model.Description" />
        </div>

        <div class="form-group">
            <label>ActualAmount</label>
            <input class="form-control" name="ActualAmount" value="@Model.ActualAmount" />
        </div>

        <div class="form-group">
            <label>StartingTime</label>
            <input class="form-control" name="StartingTime" value="@Model.StartingTime" />
        </div>

        <div class="form-group">
            <label>EndingTime</label>
            <input class="form-control" name="EndingTime" value="@Model.EndingTime" />
        </div>

        @*--------home work-------*@
        <div class="form-group">
            <label>Select pictures</label>
            <input id="AuctionPictures" class="form-control" name="AuctionPictures" type="file" multiple />
            <div id="picturesArea" class="mt-2"></div>
            @if (Model.AuctionPicturesList != null && Model.AuctionPicturesList.Count > 0)
            {
                foreach (var picture in Model.AuctionPicturesList)
                {
                    <img class='image img-thumbnail' src='/Content/images/@picture.Picture.URL' data-id="@picture.ID" style="width:200px; height:200px" />
                }
            }
            <input type="hidden" name="Auctionpictures" id="pictureIDs" />
        </div>
        @*----------------------------*@


    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button class="btn btn-primary" type="button" id="SaveButton">Save</button>
    </div>
</form>

<script>
     RemoveImageOnClick();
    $("#SaveButton").click(function () {

            var imageIDs = [];
        $("#picturesArea .image").each(function () {
            var imageID = $(this).attr("data-id");
            imageIDs.push(imageID);
        });
        $("#pictureIDs").val(imageIDs.join());
            $.ajax({
                url: "@Url.Action("edit","Auctions")",
                method: "post",
                data: $("#EditForm").serialize()
            }).done(function (response) {
                debugger;
                $("#listArea").html(response);
                $("#formModal").modal("toggle");
            });
        });
    //-------------------------Home Work-----------------------------------------------
          $("#AuctionPictures").change(function () {
        var pictures = this.files;
        var picsData = new FormData();
        for (var i = 0; i < pictures.length; i++) {
            picsData.append("Picture", pictures[i]);
        }
        $.ajax({
                 url: "@Url.Action("UploadPictures","Shared")",
                 method: "post",
                 data: picsData,
                 dataType: "json",
                 processData: false,
                 contentType: false

                }).done(function (responses) {
                 for (var i = 0; i < responses.length; i++) {
                var picResponse = responses[i];
                debugger;
                AttachNewImage(picResponse.pictureURL, picResponse.ID);
            }
        });
          });
    

    //-------------------------------------------------------------------------------------
</script>

DealDouble.Web/Views/Auctions/Index.cshtml
<div class="row">
    <div class="col-lg-12 mt-2">

        <div class="float-left">
            <h2>Auctions</h2>
        </div>
        <div class="float-right">
            <button class="btn btn-success text-right" id="createauction" data-toggle="modal" data-target="#formModal">
                Create new auction
            </button>
        </div>
        <div id="listArea">
            @{Html.RenderAction("Listing", new { categoryID = Model.CategoryID, searchTerm = Model.SearchTerm, pageNo = Model.PageNo });}
        </div>

    </div>

    <!-- Modal -->
    <div class="modal fade" id="formModal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content" id="ContentArea">

            </div>
        </div>
    </div>
</div>

<div id="imageTemplate" style="display:none">
    <img class='image img-thumbnail' src='' style="width:200px; height:200px"/>
</div>

<script>
       $("#createauction").click(function () {
           $.ajax({
               url: "@Url.Action("Create","Auctions")",
               type: "get"
           }).done(function (response) {
               $("#formModal").modal("toggle");
               $("#ContentArea").html(response);
           });
       });

    function AttachNewImage(imageURL, imageID) {
        var $newImgHtml = $("#imageTemplate").clone();
        $newImgHtml.find(".image").attr("src", "/content/images/" + imageURL);
        $newImgHtml.find(".image").attr("data-id", imageID);
        $("#picturesArea").append($newImgHtml.html());

        RemoveImageOnClick();
    }

    function RemoveImageOnClick() {
        $("#picturesArea .image").click(function () {
            $(this).remove();
        });
    }

    function ReloadListing() {
         $.ajax({
               url: "@Url.Action("Listing","Auctions")",
               type: "get"
           }).done(function (response) {
               $("#listArea").html(response);
           });
        
    }
</script>

DealDouble.Web/Views/Auctions/Listing.cshtml
@model DealDouble.Web.ViewModels.AuctionListingViewModel



    <div>
        <table class="table table-hover">
            <thaed>
                <tr>
                    <th> Title</th>
                    <th> Category</th>
                    <th> Descrition</th>
                    <th> ActualAmount</th>
                    <th> StartingTime</th>
                    <th> EndingTime</th>
                    <th> Actions</th>

                </tr>
            </thaed>
            <tbody>
                @foreach (var auction in Model.Auctions)
                {
                    <tr>
                        <td> @auction.Title</td>
                        <td> @auction.Category.Name</td>
                        <td>
                            @auction.Description
                        </td>
                        <td>
                            @auction.ActualAmount
                        </td>
                        <td>
                            @auction.StartingTime
                        </td>
                        <td>
                            @auction.EndingTime
                        </td>
                        <td>
                            <button class=" DeleteBtn btn btn-danger" data_id="@auction.ID">Delete</button>
                            <button class="EditBtn btn btn-primary" data_id="@auction.ID" data-toggle="modal" data-target="#formModal">Edit</button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        @if (Model.Pager != null && Model.Pager.TotalPages > 0)
        {
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">

                    @if (Model.Pager.CurrentPage == 1)
                    {
                        <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                    }
                    else
                    {
                        <li class="page-item">
                            <a class="page-link" href="@Url.Action("Index", "Auctions",new { pageNo=Model.Pager.CurrentPage - 1 })">
                                Previous
                            </a>
                        </li>
                    }

                    @for (int page = Model.Pager.StartPage; page < Model.Pager.EndPage + 1; page++)
                    {
                        var active = page == Model.Pager.CurrentPage ? "active" : string.Empty;
                        <li class="page-item @active">
                            <a class="page-link" href="@Url.Action("Index", "Auctions",new { pageNo=page })">@page</a>
                        </li>
                    }

                    @if (Model.Pager.CurrentPage == Model.Pager.EndPage)
                    {
                        <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                    }
                    else
                    {
                        <li class="page-item">
                            <a class="page-link" href="@Url.Action("Index", "Auctions",new { pageNo=Model.Pager.CurrentPage + 1 })">
                                Next
                            </a>
                        </li>
                    }
                </ul>
            </nav>
        }

    </div>


<script>
            $(".EditBtn").click(function () {
                    $.ajax({
                        url: "@Url.Action("edit","Auctions")",
                        method: "get",
                        data: {
                            ID: $(this).attr("data_id")
                        }
                    }).done(function (response) {
                        $("#ContentArea").html(response);
                    });
            });
    
                $(".DeleteBtn").click(function () {
                    var result = confirm("Are you sure to delete this Auction!");
                    if (result == true) {
                        $.ajax({
                            url: "@Url.Action("delete","Auctions")",
                            method: "post",
                            data: {
                                ID: $(this).attr("data_id")
                            }
                        }).done(function (response) {
                            $("#listArea").html(response);
                        });
                    }
                });


</script>